### ISSUE TITLE
Execute cron on last day of every month

### ISSUE THREAD

**Issue by nagainfosolutions** [ncb000gt/node-cron#240] opened 2016-07-22 09:44 UTC
Hi,
I couldn't find out any solution for execute cron on last day of every month. 
Kindly help me to achieve this :)

**Comment by ultimate-tester** [comment] 2016-08-09 14:16
0 0 3 L * ?

**Comment by ultimate-tester** [comment] 2016-08-09 14:22
Duplicate of #210

**Comment by ncb000gt** [comment] 2016-10-07 00:45
Closing as it's a duplicate. Please see linked ticket.

**Closed by ncb000gt** 2016-10-07 00:45 UTC
